export const augustFiveArchivePhotos = [
  { src: "/photos/august-5/malaita-baptism.jpg", alt: "Missionaries and members gathered at a beach baptism on Malaita", caption: "Malaita baptism" },
  { src: "/photos/august-5/teaching-selfie.jpg", alt: "Two missionaries teaching in a hillside neighborhood", caption: "Teaching on Guadalcanal" },
  { src: "/photos/august-5/walking-neighborhood.jpg", alt: "Two sister missionaries walking through a neighborhood", caption: "Sisters on their way" },
  { src: "/photos/august-5/porch-teaching.jpg", alt: "Missionaries visiting with people beneath a porch awning", caption: "Sharing testimonies" },
  { src: "/photos/august-5/family-teaching-selfie.jpg", alt: "Missionaries smiling with a family during a teaching visit", caption: "A joyful teaching visit" },
  { src: "/photos/august-5/guadalcanal-memorial.jpg", alt: "President and Sister Court at the Guadalcanal American Memorial", caption: "Guadalcanal American Memorial" },
  { src: "/photos/august-5/memorial-flags.jpg", alt: "American and Solomon Islands flags flying over the Guadalcanal memorial", caption: "Remembering those who served" },
  { src: "/photos/august-5/courts-memorial-selfie.jpg", alt: "President and Sister Court at the memorial wall", caption: "At the memorial wall" },
  { src: "/photos/august-5/independence-cake.jpg", alt: "A cake decorated as an American flag for the 250th anniversary", caption: "Celebrating 250 years" },
  { src: "/photos/august-5/embassy-reception.jpg", alt: "President and Sister Court with guests at the US Embassy reception", caption: "The US Embassy reception" },
  { src: "/photos/august-5/fhe-living-room.jpg", alt: "Missionaries and senior couples gathered in a living room for Family Home Evening", caption: "Family Home Evening together" },
  { src: "/photos/august-5/fhe-group.jpg", alt: "Missionaries smiling together during Family Home Evening", caption: "Learning from each other" },
  { src: "/photos/august-5/fhe-dinner.jpg", alt: "Missionaries and senior couples gathered around a dinner table", caption: "A good meal and good company" },
  { src: "/photos/august-5/rainy-senior-missionaries.jpg", alt: "Senior missionaries smiling together on a rainy day", caption: "Our senior missionaries" },
  { src: "/photos/august-5/cocoa-farm-couple.jpg", alt: "President and Sister Court standing among cocoa trees", caption: "Amazing Grace Cocoa Farm" },
  { src: "/photos/august-5/cocoa-art.jpg", alt: "Local artwork displayed at the cocoa farm", caption: "Art at the family plantation" },
  { src: "/photos/august-5/cocoa-display.jpg", alt: "Colorful cocoa farm crafts and baskets", caption: "Made at the plantation" },
  { src: "/photos/august-5/cocoa-grinder.jpg", alt: "President Court working a wooden cocoa grinder", caption: "Learning how cocoa is produced" },
  { src: "/photos/august-5/coconut-harvest.jpg", alt: "President and Sister Court holding a freshly husked coconut", caption: "Fresh from the farm" },
  { src: "/photos/august-5/beach-dog.jpg", alt: "President Court standing near the beach with a dog", caption: "Tenaru Beach" },
  { src: "/photos/august-5/husking-coconut.jpg", alt: "Sister Court husking a coconut", caption: "Husking a coconut" },
  { src: "/photos/august-5/bananas.jpg", alt: "Sister Court standing beneath a bunch of bananas", caption: "Finding the bananas" },
  { src: "/photos/august-5/grace-cocoa-farmer.jpg", alt: "Grace holding produce from her cocoa farm", caption: "Grace and her family plantation" },
  { src: "/photos/august-5/omae-family-airport.jpg", alt: "The O’mae family together at the airport", caption: "The O’mae family" },
  { src: "/photos/august-5/elder-samia-airport.jpg", alt: "Elder Samia with family and missionaries at the airport", caption: "Elder Samia" },
  { src: "/photos/august-5/fanasia-family.jpg", alt: "The Fanasia family with President and Sister Court", caption: "The Fanasia family" },
  { src: "/photos/august-5/naha-house-missionaries.jpg", alt: "Missionaries and senior couples together above the former Naha house", caption: "Goodbye to the Naha House" },
  { src: "/photos/august-5/missionaries-together.jpg", alt: "A large group of missionaries gathered outside a meetinghouse", caption: "Missionaries together" },
  { src: "/photos/august-5/elder-wilkerson-airport.jpg", alt: "Elder Wilkerson arriving at the Honiara airport", caption: "Welcome, Elder Wilkerson" },
  { src: "/photos/august-5/diesel-drum-shed.jpg", alt: "Missionaries moving a fuel drum from a storage shed", caption: "The empty drum" },
  { src: "/photos/august-5/diesel-team.jpg", alt: "Missionaries standing with a full fuel drum on Malaita", caption: "The full drum arrives" },
  { src: "/photos/august-5/fueling-mission-vehicle.jpg", alt: "President Court pouring diesel into the mission vehicle", caption: "One pitcher at a time" },
  { src: "/photos/august-5/malaita-branch.jpg", alt: "Missionaries and branch members gathered at a meetinghouse on Malaita", caption: "The Saints on Malaita" },
  { src: "/photos/august-5/children-watching-baptism.jpg", alt: "Children and families who watched a baptism from beneath the trees", caption: "Watching the baptism from the trees" },
] as const;

export const monthOneArchivePhotos = [
  { src: "/photos/hero-sunset.jpg", alt: "President and Sister Court together near the water at sunset", caption: "President and Sister Court" },
  { src: "/photos/bags-arrive.jpg", alt: "President and Sister Court with missionaries and their recovered luggage", caption: "The bags arrive" },
  { src: "/photos/fauabu-baptisms.jpg", alt: "Missionaries and newly baptized members standing on a beach at Fauabu, Malaita", caption: "Fauabu baptisms" },
  { src: "/photos/opening-celebration.jpg", alt: "Solomon Islanders performing at the celebration opening the new mission", caption: "Opening celebration" },
  { src: "/photos/mission-leadership-council.jpg", alt: "President and Sister Court with the first Mission Leadership Council", caption: "Mission Leadership Council" },
  { src: "/photos/talise-baptisms.jpg", alt: "Missionaries and newly baptized members outside the Talise Chapel", caption: "Talise baptisms" },
  { src: "/photos/companionship-study.jpg", alt: "President and Sister Court visiting missionaries for companionship study", caption: "Companionship study" },
  { src: "/photos/family-home-evening.jpg", alt: "President and Sister Court with the Point Cruz District missionaries", caption: "Family Home Evening" },
  { src: "/photos/auki-baptisms.jpg", alt: "Missionaries and newly baptized members on a beach in Malaita", caption: "Auki baptisms" },
  { src: "/photos/local-food.jpg", alt: "A whole cooked fish served with green beans", caption: "Local food" },
  { src: "/photos/hero-national-news.jpg", alt: "President and Sister Court speaking with a reporter in Honiara", caption: "National television news" },
  { src: "/photos/honiara-traffic.jpg", alt: "Night traffic on a road in Honiara", caption: "Honiara traffic" },
  { src: "/photos/opening-youth.jpg", alt: "Young Solomon Island women at the mission opening celebration", caption: "Mission opening celebration" },
  { src: "/photos/opening-men.jpg", alt: "Two Solomon Island men smiling at the mission opening celebration", caption: "Mission opening celebration" },
  { src: "/photos/opening-boys.jpg", alt: "Three boys smiling at the mission opening celebration", caption: "Mission opening celebration" },
  { src: "/photos/opening-girls.jpg", alt: "Four girls at the mission opening celebration", caption: "Mission opening celebration" },
  { src: "/photos/branch-members.jpg", alt: "Missionaries standing with local branch members", caption: "Branch members and missionaries" },
  { src: "/photos/green-valley.jpg", alt: "Two missionaries walking through a Green Valley neighborhood", caption: "Green Valley" },
  { src: "/photos/district-leaders.jpg", alt: "President and Sister Court with district and branch leaders and their wives", caption: "District and branch leaders" },
  { src: "/photos/senior-missionaries.jpg", alt: "President and Sister Court with the senior missionaries", caption: "Senior missionaries" },
  { src: "/photos/naha-sisters.jpg", alt: "Sister Kagl and Sister Takifu walking through a neighborhood in Naha", caption: "Sister Kagl and Sister Takifu" },
  { src: "/photos/water-tanks.jpg", alt: "Blue water tanks donated for humanitarian aid", caption: "Water tanks" },
  { src: "/photos/wheelchair.jpg", alt: "A Solomon Islander using a donated wheelchair", caption: "Mobility support" },
] as const;
